### ISSUE TITLE
Serial lib not found

### ISSUE THREAD

**Issue by gilardin10** [RobustFieldAutonomyLab/videoray#1]
![image](https://user-images.githubusercontent.com/14967107/35580952-60d71ee6-05e2-11e8-9f8b-e9fb8c30f232.png)
Hello, I really appreciated this update to the humans-master project. I'm currently working with a Videoray Pro 4, so this project is really useful. Unfortunately, I'm having some issues trying to run this project, I followed all your instructions but I have this issue that I tried to solve for several days, without success.

Can you help me?

**Comment by jinkunw** [comment]
It seems the serial port `/dev/videoray` doesn't exist on your machine. Can you see VideoRay's serial port by running `ls -la /dev/ttyUSB*`? If you find it with name `/dev/ttyUSB1`, then change the port in the launch file.

**Comment by gilardin10** [comment]
Thank you for your help. I was checking this /dev before, but just for the controller, it didn't cross my mind that the videoray's serial could be also in a different port.

So, I solve this mistake, but of course, after one mistake it comes other. Unfortunately, I have the ROV without any extras, so no DVL neither tritech micron. Because of that I'm getting some error during the runtime of videoray_launch.launch
![image](https://user-images.githubusercontent.com/14967107/35631954-3240c21a-069d-11e8-8742-d966e02462bf.png)

I tried to delete the pkgs (tritech/DVL) from the launch files, but without success, because doing the catkin_cmake more and more errors appear, because these commands are present in the cmake files and my knowledge about this is kind of basic.
Do you have some tip to run this without these extra tools? I'd really appreciated.

Best regards.

**Comment by jinkunw** [comment]
I have updated the control package, and now you can disable DVL in the launch file.

**Comment by gilardin10** [comment]
Hi again,

Thank you for the update, it was very useful.  And sorry to bother with this, but I still have one problem (I think it's the last one), when I launch the videoray.control I get this error message. I looked into the code and I understand where is this error, but I don't know why, can you help me one last time, please?

![nav data error](https://user-images.githubusercontent.com/14967107/35739790-affdadc4-082a-11e8-8f55-3d6d9c3fd255.png)

I changed the /dev/videoray to /dev/ttyUSB0, so I guess it's not a problem with the wrong door connection.

Also, the videoray.input it's running in the console, but I can't control with my joystick (it was supposed right? 
![videoray_input](https://user-images.githubusercontent.com/14967107/35739874-f99e3066-082a-11e8-8ab8-7eedfabc3854.png)

Then, if you don't mind to explain me better what's the difference between the launch files? Because it seems that with the videoray_launch I can control and have the camera image, right?

Thank you again for your help

**Comment by jinkunw** [comment]
1. Can you uncomment the code from line 232 to line 235 to see if the packet is received succcessfully?
2. As for the js, can you see the `/videoray_input/throttle` is published?
3. The launch file in `videoray_launch` is used to launch all modules in individual packages. However, camera hasn't been added yet.

**Comment by gilardin10** [comment]
Hello again,

Sorry for the delay, once again I was just able to test this today.  
I still have problems, sometimes there's no error message, but nothing is working, I mean the USB serial adapter is with the lights on (what it means that it's transferring data), but I can't control with the joystick.

![image](https://user-images.githubusercontent.com/14967107/35981982-8a72162e-0ce6-11e8-9ea4-1d82b721f53c.png)

If I try several times, I get this error ^ 

What am I doing wrong?

**Comment by jinkunw** [comment]
The serial exception happends mostly because of the permission. Before launching the videoray_control, change its permission on serial port by `sudo chmod 777 /dev/ttyUSB0`.

Also it appears you didn't launch the js package? Try `roslaunch videoray_launch videoray.launch micron:=false dvl:=false js:=true` (change the device names in the launch file first).
